
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EDGE EDGES EDGE_VALUE FROM ID NUM SINK START TERMINAL TO VERTICESexpression : VERTICES NUMexpression : EDGES NUMexpression : FROM NUM TO NUM EDGE EDGE_VALUEexpression : TERMINAL NUMexpression : START NUM'
    
_lr_action_items = {'VERTICES':([0,],[2,]),'EDGES':([0,],[3,]),'FROM':([0,],[4,]),'TERMINAL':([0,],[5,]),'START':([0,],[6,]),'$end':([1,7,8,10,11,15,],[0,-1,-2,-4,-5,-3,]),'NUM':([2,3,4,5,6,12,],[7,8,9,10,11,13,]),'TO':([9,],[12,]),'EDGE':([13,],[14,]),'EDGE_VALUE':([14,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> VERTICES NUM','expression',2,'p_expression_vertices','parser.py',7),
  ('expression -> EDGES NUM','expression',2,'p_expression_edges','parser.py',12),
  ('expression -> FROM NUM TO NUM EDGE EDGE_VALUE','expression',6,'p_expression_edge','parser.py',17),
  ('expression -> TERMINAL NUM','expression',2,'p_expression_terminal','parser.py',23),
  ('expression -> START NUM','expression',2,'p_expression_root','parser.py',28),
]
