
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ELSE ID IF LBR MULT NUM PLUS RBR THENif : IF expression THEN if ELSE if\n        | IF expression THEN if\n        | expression expression : expression PLUS expressionexpression : termterm : term MULT factorterm : factorfactor : NUMfactor : LBR expression RBR'
    
_lr_action_items = {'IF':([0,12,17,],[2,2,2,]),'NUM':([0,2,7,9,10,12,17,],[6,6,6,6,6,6,6,]),'LBR':([0,2,7,9,10,12,17,],[7,7,7,7,7,7,7,]),'$end':([1,3,4,5,6,13,14,15,16,18,],[0,-3,-5,-7,-8,-4,-6,-9,-2,-1,]),'ELSE':([3,4,5,6,13,14,15,16,18,],[-3,-5,-7,-8,-4,-6,-9,17,-1,]),'PLUS':([3,4,5,6,8,11,13,14,15,],[9,-5,-7,-8,9,9,9,-6,-9,]),'THEN':([4,5,6,8,13,14,15,],[-5,-7,-8,12,-4,-6,-9,]),'RBR':([4,5,6,11,13,14,15,],[-5,-7,-8,15,-4,-6,-9,]),'MULT':([4,5,6,14,15,],[10,-7,-8,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'if':([0,12,17,],[1,16,18,]),'expression':([0,2,7,9,12,17,],[3,8,11,13,3,3,]),'term':([0,2,7,9,12,17,],[4,4,4,4,4,4,]),'factor':([0,2,7,9,10,12,17,],[5,5,5,5,14,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> if","S'",1,None,None,None),
  ('if -> IF expression THEN if ELSE if','if',6,'p_if','parse.py',9),
  ('if -> IF expression THEN if','if',4,'p_if','parse.py',10),
  ('if -> expression','if',1,'p_if','parse.py',11),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','parse.py',22),
  ('expression -> term','expression',1,'p_expression_term','parse.py',26),
  ('term -> term MULT factor','term',3,'p_term_times','parse.py',30),
  ('term -> factor','term',1,'p_term_factor','parse.py',34),
  ('factor -> NUM','factor',1,'p_factor_num','parse.py',38),
  ('factor -> LBR expression RBR','factor',3,'p_factor_expr','parse.py',42),
]
